### ISSUE TITLE
 TELL ME WHY

### ISSUE THREAD

**Issue by Syntex1337** [ringo360/ringo360#2]
TELL ME WHY

**Comment by ringo360** [comment]
**bruh**
 I am just building a website on WordPress.

proof: 
![proof-issue2](https://user-images.githubusercontent.com/105296365/232023791-4e13e493-b4d1-40d5-a826-9da7df7cb1c7.png)

**Comment by ringo360** [comment]
I pressed STAR but did not fork.

**Comment by ringo360** [comment]
**Are you sure you're not mistaken???????????**

**Comment by ringo360** [comment]
No reply, so I'm closing the issue 😂.
If you still have a complaint, come to Discord.
Discord: ringoXD#1202
